### ISSUE TITLE
Losing metadata columns in readToTargets function

### ISSUE THREAD

**Issue by sarubin** [markrobinsonuzh/crispRvariants#10]
Hi, I am having an issue with the readToTargets function in which my metadata columns (name and score) seem to disappear in the crispr_set that is created even though they are read in correctly into a GRanges object. I've found a workaround for my current analysis, but it may make more complicated analyses more challenging if this data continues to be lost in the initial assignment of the crispr_set. I'm not sure if this is an issue with the readToTargets function in the context of my inputs, but I would greatly appreciate your advice with this problem. Thank you!

In case it is helpful, here is how I am assigning crispr_set and the output that I get when running the code:
  crispr_set <- readsToTargets(file.path(samples[[i]]$bamfile), targets = gdl[gene_idx], references = reference[gene_idx], names = samples[[i]]$group, target.loc = 17, verbose=TRUE)

Output (before crispr_set, my GRanges object):

CrisprSet object containing 1 CrisprRun samples

Target location:

GRanges object with 1 range and 1 metadata column:
        seqnames    ranges strand |        name
           <Rle> <IRanges>  <Rle> | <character>
  [1] genome    17-39      + |      guide1
  -------

  seqinfo: 1 sequence from an unspecified genome; no seqlengths
...

Output(crispr_set):

crispr_set
[[1]]
CrisprSet object containing 1 CrisprRun samples
Target location:
GRanges object with 1 range and 0 metadata columns:
        seqnames    ranges strand
           <Rle> <IRanges>  <Rle>
  [1] genome     17-39      +
  -------
  seqinfo: 1 sequence from an unspecified genome; no seqlengths_

**Comment by HLindsay** [comment]
Hi, 

Thanks for letting me know about this.  I've pushed a fix in devel version 1.9.1 (**edited: make that version 1.9.2!**).  If you prefer to keep using the release version for the moment, as a workaround you could either use `readsToTarget` instead of `readsToTargets` if this works with your experimental design, or the way the code is structured at the moment also allows you to replace the metadata columns manually:

```{R}
mcols(crispr_set$target) <- mcols(gdl)
``` 

Best,
Helen

**Comment by sarubin** [comment]
Thanks for the help and advice!
