### ISSUE TITLE
Filtering mutationtypes in plotVariants

### ISSUE THREAD

**Issue by LudvigEk** [markrobinsonuzh/crispRvariants#3]
Hi!
Im trying to visualize indels with the plotVariants function, but I cannot find an option to remove SNVs. 
I was hoping include.nonindel=FALSE which can be used in variantCounts() would work, but it didn't. 

var_count<-variantCounts(crispr_set[[92]],include.nonindel=FALSE)
p <- plotVariants(crispr_set[[92]], include.nonindel=FALSE)

Any way to set that up?

regards
Ludvig Ekdahl

**Comment by HLindsay** [comment]
Hi Ludvig,

This is a bit complicated to do in the current Bioconductor release version.  You'd have to construct the allele plot, heatmap and transcript plots separately.  The transcript plot is created with the non-exported function `annotateGenePlot` and the layout with `arrangePlots`, also non-exported.  For modifying the allele plot in the release version:

```R
library(CrispRVariants)
data("gol_clutch1")
# Get the arguments that are passed to the plot, but do not actually plot
plot.args <- plotAlignments(gol, create.plot = FALSE)
# Filter to keep the alignments you want, e.g.
plot.args$alns <- plot.args$alns[! names(plot.args$alns) == "-1:3I,5:21I"]
p <- do.call(plotAlignments, plot.args)
````
I've been working on making this easier in the devel version.  I've just pushed an update (devel version 1.5.1) which introduces an `alleles` argument to `plotAlignments` and `plotFreqHeatmap`.  To use this, you'd need a list of the alleles you want to include, e.g. the rownames from `variantCounts`.  For example:

```R
library(CrispRVariants)
data("gol_clutch1")
plotAlignments(gol, alleles = c("-14:10D","-9:3D","2:24I"))
```
This means that you can still use `plotVariants` by including the allele names in  `plotAlignments.args` and `plotFreqHeatmap.args`.

If using the devel version isn't a possibility for you, let me know and I'll give you some more detailed code for using the non-exported functions.  I could also make `plotVariants` work with the same filtering arguments as `variantCounts`.  Would the default header options for `plotFreqHeatmap` (total read counts or percentage with indels) still make sense in your case?

Best,
Helen

**Comment by LudvigEk** [comment]
Hi Helen, thanks for the quick reply! 
I'm using the bioconductor version, 1.4.0. 
I could try picking up the devel branch but have some bad experiences setting things up with devtools in general... 
If you have pushed the 1.5.1 version recently then can I expect that to come to bioconductor in the coming weeks or so? If this is the case I might simply wait for that. If you mean that it's pushed to this repository only I will try setting up the devel-branch.

To me it makes sense being able to use similar filtering options for plotVariants and variantCounts to be able to see what's been filtered and counted in an intuitive manner. 

I only use the total read count option and that would still make sense.

regards
Ludvig

**Comment by HLindsay** [comment]
Hi Ludvig,

I've now allowed `plotAlignments` and `plotFreqHeatmap` to accept the same arguments as `variantCounts` in devel version 1.5.3.  Thanks for the suggestion!  This change should appear on [Bioconductor devel](https://bioconductor.org/packages/devel/bioc/html/CrispRVariants.html) in the next few days and is already in the [Bioconductor Github mirror](https://github.com/Bioconductor-mirror/CrispRVariants).  It won't appear in Bioconductor release until towards the end of the year.

To use `include.nonindel` with `plotVariants`, it needs to be added to both `plotAlignments.args`
and `plotFreqHeatmap.args`, e.g.

```R
plotVariants(crispr_set, plotAlignments.args = list(include.nonindel = FALSE),
                     plotFreqHeatmap.args = list(include.nonindel = FALSE))
```
I'm aiming to make this syntax a bit more concise soon, but the above will still work.

I haven't kept this repo up to date with the Bioconductor package.  It's really a record of the package development pre-Bioconductor, as I didn't manage to integrate the package history into the Bioconductor repo.   Bioconductor is in the process of changing to a fully git based version control system.  When this is finished the new Bioconductor Github repo will become the main one.  

Best,
Helen

**Comment by LudvigEk** [comment]
Great work, thanks a lot!
The heatmap is acting up for me though and still seem to plot all counts, see below.

```
> plotVariants(crispr_set[[92]], plotAlignments.args = list(include.nonindel = FALSE),
+              plotFreqHeatmap.args = list(include.nonindel = FALSE))
```

![no_snv](https://user-images.githubusercontent.com/29398826/28355768-b8bd0aa6-6c65-11e7-9ad3-a18812e9be2c.jpg)


regards
Ludvig
